//
//  Rivalry.swift
//  MAC APP Like ESPN
//
//  Created by Alex Scheer on 5/9/23.
//

import Foundation

struct Rivalry: Identifiable {
    let id = UUID()
    let name: String
    let teams: [RivalryTeam]
    let history: [RivalryResult]
    let michiganMACTrophy: [MichiganMACTrophy]
    
    init(name: String, teams: [RivalryTeam], history: [RivalryResult], michiganMACTrophy: [MichiganMACTrophy] = []) {
        self.name = name
        self.teams = teams
        self.history = history
        self.michiganMACTrophy = michiganMACTrophy
    }

}

struct RivalryResult {
    var year: String
    var winner: String
    var winnerScore: String
    var loser: String
    var loserScore: String
}


struct RivalryTeam: Identifiable {
    let id = UUID()
    let name: String
    let logo: String
}

struct MichiganMACTrophy {
    let year: String
    let trophyWinner: String
    let records: (String, String, String)
    let firstMatch: String
    let secondMatch: String
    let thirdMatch: String
    
    var winCounts: (Int, Int, Int) {
        let winCountComponents = [
            Int(records.0.replacingOccurrences(of: "–", with: "")) ?? 0,
            Int(records.1.replacingOccurrences(of: "–", with: "")) ?? 0,
            Int(records.2.replacingOccurrences(of: "–", with: "")) ?? 0
        ]
        return (winCountComponents[0], winCountComponents[1], winCountComponents[2])
    }
}

let akron = RivalryTeam(name: "Akron", logo: "Akron")
let kentState = RivalryTeam(name: "Kent State", logo: "Kent_State")
let ballState = RivalryTeam(name: "Ball State", logo: "Ball_State")
let northernIllinois = RivalryTeam(name: "Northern Illinois", logo: "Northern_Illinois")
let bowlingGreen = RivalryTeam(name: "Bowling Green", logo: "Bowling_Green")
let toledo = RivalryTeam(name: "Toledo", logo: "Toledo")
let centralMichigan = RivalryTeam(name: "Central Michigan", logo: "Central_Michigan")
let westernMichigan = RivalryTeam(name: "Western Michigan", logo: "Western_Michigan")
let miami = RivalryTeam(name: "Miami OH", logo: "Miami_OH")
let ohio = RivalryTeam(name: "Ohio", logo: "Ohio")
let easternMichigan = RivalryTeam(name: "Eastern Michigan", logo: "Eastern_Michigan")

let wagonWheelHistory: [RivalryResult] = [
    RivalryResult(year: "1923", winner: "Akron", winnerScore: "32", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1928", winner: "Akron", winnerScore: "8", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1929", winner: "Akron", winnerScore: "25", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1930", winner: "Akron", winnerScore: "12", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1931", winner: "Akron", winnerScore: "12", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1932", winner: "Akron, Kent State", winnerScore: "0", loser: "Akron, Kent State", loserScore: "0"),
    RivalryResult(year: "1933", winner: "Akron", winnerScore: "19", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1934", winner: "Akron", winnerScore: "26", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1935", winner: "Akron", winnerScore: "3", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1936", winner: "Akron", winnerScore: "6", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1940", winner: "Akron", winnerScore: "23", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1941", winner: "Akron", winnerScore: "41", loser: "Kent State", loserScore: "13"),
    RivalryResult(year: "1942", winner: "Kent State", winnerScore: "23", loser: "Akron", loserScore: "6"),
    RivalryResult(year: "1946", winner: "Kent State", winnerScore: "13", loser: "Akron", loserScore: "6"),
    RivalryResult(year: "1947", winner: "Kent State", winnerScore: "6", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1948", winner: "Kent State", winnerScore: "31", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1949", winner: "Kent State", winnerScore: "47", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1950", winner: "Kent State", winnerScore: "19", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1951", winner: "Kent State", winnerScore: "48", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1952", winner: "Kent State", winnerScore: "34", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1953", winner: "Kent State", winnerScore: "20", loser: "Akron", loserScore: "19"),
    RivalryResult(year: "1954", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1972", winner: "Akron, Kent State", winnerScore: "13", loser: "Akron, Kent State", loserScore: "13"),
    RivalryResult(year: "1974", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1979", winner: "Kent State", winnerScore: "18", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1980", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "9"),
    RivalryResult(year: "1981", winner: "Kent State", winnerScore: "17", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1983", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1984", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "6"),
    RivalryResult(year: "1985", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "3"),
    RivalryResult(year: "1986", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "9"),
    RivalryResult(year: "1987", winner: "Kent State", winnerScore: "24", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1988", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "10"),
    RivalryResult(year: "1989", winner: "Kent State", winnerScore: "24", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1990", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1992", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1993", winner: "Kent State", winnerScore: "17", loser: "Akron", loserScore: "10"),
    RivalryResult(year: "1994", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1995", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "1996", winner: "Kent State", winnerScore: "24", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "1997", winner: "Kent State", winnerScore: "17", loser: "Akron", loserScore: "10"),
    RivalryResult(year: "1998", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "1999", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "2000", winner: "Kent State", winnerScore: "24", loser: "Akron", loserScore: "7"),
    RivalryResult(year: "2001", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "10"),
    RivalryResult(year: "2002", winner: "Kent State", winnerScore: "21", loser: "Akron", loserScore: "14"),
    RivalryResult(year: "2003", winner: "Kent State", winnerScore: "41", loser: "Akron", loserScore: "38"),
    RivalryResult(year: "2004", winner: "Akron", winnerScore: "24", loser: "Kent State", loserScore: "19"),
    RivalryResult(year: "2005", winner: "Akron", winnerScore: "35", loser: "Kent State", loserScore: "3"),
    RivalryResult(year: "2006", winner: "Kent State", winnerScore: "37", loser: "Akron", loserScore: "15"),
    RivalryResult(year: "2007", winner: "Akron", winnerScore: "27", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "2008", winner: "Akron", winnerScore: "30", loser: "Kent State", loserScore: "27"),
    RivalryResult(year: "2009", winner: "Akron", winnerScore: "28", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "2010", winner: "Kent State", winnerScore: "28", loser: "Akron", loserScore: "17"),
    RivalryResult(year: "2011", winner: "Kent State", winnerScore: "35", loser: "Akron", loserScore: "3"),
    RivalryResult(year: "2012", winner: "Kent State", winnerScore: "35", loser: "Akron", loserScore: "24"),
    RivalryResult(year: "2013", winner: "Akron", winnerScore: "16", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "2014", winner: "Kent State", winnerScore: "27", loser: "Akron", loserScore: "24"),
    RivalryResult(year: "2015", winner: "Akron", winnerScore: "20", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "2016", winner: "Akron", winnerScore: "31", loser: "Kent State", loserScore: "27"),
    RivalryResult(year: "2017", winner: "Akron", winnerScore: "24", loser: "Kent State", loserScore: "14"),
    RivalryResult(year: "2018", winner: "Akron", winnerScore: "24", loser: "Kent State", loserScore: "23"),
    RivalryResult(year: "2019", winner: "Kent State", winnerScore: "26", loser: "Akron", loserScore: "3"),
    RivalryResult(year: "2020", winner: "Kent State", winnerScore: "69", loser: "Akron", loserScore: "35"),
    RivalryResult(year: "2021", winner: "Kent State", winnerScore: "38", loser: "Akron", loserScore: "0"),
    RivalryResult(year: "2022", winner: "Kent State", winnerScore: "33", loser: "Akron", loserScore: "27")
    ]

let battleOfI75History: [RivalryResult] = [
    RivalryResult(year: "1919", winner: "Bowling Green", winnerScore: "6", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1921", winner: "Toledo", winnerScore: "20", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1922", winner: "Bowling Green, Toledo", winnerScore: "6", loser: "Bowling Green, Toledo", loserScore: "6"),
    RivalryResult(year: "1923", winner: "Toledo", winnerScore: "27", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1924", winner: "Toledo", winnerScore: "12", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1928", winner: "Bowling Green", winnerScore: "14", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1929", winner: "Bowling Green, Toledo", winnerScore: "0", loser: "Bowling Green, Toledo", loserScore: "0"),
    RivalryResult(year: "1930", winner: "Bowling Green, Toledo", winnerScore: "0", loser: "Bowling Green, Toledo", loserScore: "0"),
    RivalryResult(year: "1932", winner: "Bowling Green", winnerScore: "12", loser: "Toledo", loserScore: "6"),
    RivalryResult(year: "1933", winner: "Toledo", winnerScore: "26", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1934", winner: "Toledo", winnerScore: "22", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1935", winner: "Toledo", winnerScore: "63", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1948", winner: "Bowling Green", winnerScore: "21", loser: "Toledo", loserScore: "6"),
    RivalryResult(year: "1949", winner: "Toledo", winnerScore: "20", loser: "Bowling Green", loserScore: "19"),
    RivalryResult(year: "1950", winner: "Bowling Green", winnerScore: "39", loser: "Toledo", loserScore: "14"),
    RivalryResult(year: "1951", winner: "Toledo", winnerScore: "12", loser: "Bowling Green", loserScore: "6"),
    RivalryResult(year: "1952", winner: "Bowling Green", winnerScore: "29", loser: "Toledo", loserScore: "19"),
    RivalryResult(year: "1953", winner: "Toledo", winnerScore: "20", loser: "Bowling Green", loserScore: "19"),
    RivalryResult(year: "1954", winner: "Toledo", winnerScore: "38", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1955", winner: "Bowling Green", winnerScore: "39", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1956", winner: "Bowling Green", winnerScore: "34", loser: "Toledo", loserScore: "12"),
    RivalryResult(year: "1957", winner: "Bowling Green", winnerScore: "29", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1958", winner: "Bowling Green", winnerScore: "31", loser: "Toledo", loserScore: "16"),
    RivalryResult(year: "1959", winner: "Bowling Green", winnerScore: "51", loser: "Toledo", loserScore: "21"),
    RivalryResult(year: "1960", winner: "Bowling Green", winnerScore: "14", loser: "Toledo", loserScore: "3"),
    RivalryResult(year: "1961", winner: "Bowling Green", winnerScore: "17", loser: "Toledo", loserScore: "6"),
    RivalryResult(year: "1962", winner: "Bowling Green", winnerScore: "28", loser: "Toledo", loserScore: "13"),
    RivalryResult(year: "1963", winner: "Bowling Green", winnerScore: "22", loser: "Toledo", loserScore: "20"),
    RivalryResult(year: "1964", winner: "Bowling Green", winnerScore: "31", loser: "Toledo", loserScore: "14"),
    RivalryResult(year: "1965", winner: "Bowling Green", winnerScore: "21", loser: "Toledo", loserScore: "14"),
    RivalryResult(year: "1966", winner: "Bowling Green", winnerScore: "14", loser: "Toledo", loserScore: "13"),
    RivalryResult(year: "1967", winner: "Toledo", winnerScore: "33", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1968", winner: "Bowling Green, Toledo", winnerScore: "0", loser: "Bowling Green, Toledo", loserScore: "0"),
    RivalryResult(year: "1969", winner: "Toledo", winnerScore: "27", loser: "Bowling Green", loserScore: "26"),
    RivalryResult(year: "1970", winner: "Toledo", winnerScore: "20", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1971", winner: "Toledo", winnerScore: "24", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1972", winner: "Bowling Green", winnerScore: "19", loser: "Toledo", loserScore: "8"),
    RivalryResult(year: "1973", winner: "Bowling Green", winnerScore: "49", loser: "Toledo", loserScore: "35"),
    RivalryResult(year: "1974", winner: "Toledo", winnerScore: "24", loser: "Bowling Green", loserScore: "19"),
    RivalryResult(year: "1975", winner: "Bowling Green", winnerScore: "34", loser: "Toledo", loserScore: "17"),
    RivalryResult(year: "1976", winner: "Bowling Green", winnerScore: "29", loser: "Toledo", loserScore: "28"),
    RivalryResult(year: "1977", winner: "Bowling Green", winnerScore: "21", loser: "Toledo", loserScore: "13"),
    RivalryResult(year: "1978", winner: "Toledo", winnerScore: "45", loser: "Bowling Green", loserScore: "27"),
    RivalryResult(year: "1979", winner: "Toledo", winnerScore: "23", loser: "Bowling Green", loserScore: "17"),
    RivalryResult(year: "1980", winner: "Bowling Green", winnerScore: "17", loser: "Toledo", loserScore: "6"),
    RivalryResult(year: "1981", winner: "Bowling Green", winnerScore: "38", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1982", winner: "Toledo", winnerScore: "24", loser: "Bowling Green", loserScore: "10"),
    RivalryResult(year: "1983", winner: "Bowling Green", winnerScore: "6", loser: "Toledo", loserScore: "3"),
    RivalryResult(year: "1984", winner: "Toledo", winnerScore: "17", loser: "Bowling Green", loserScore: "6"),
    RivalryResult(year: "1985", winner: "Bowling Green", winnerScore: "21", loser: "Toledo", loserScore: "0"),
    RivalryResult(year: "1986", winner: "Toledo", winnerScore: "22", loser: "Bowling Green", loserScore: "3"),
    RivalryResult(year: "1987", winner: "Bowling Green", winnerScore: "20", loser: "Toledo", loserScore: "6"),
    RivalryResult(year: "1988", winner: "Toledo", winnerScore: "34", loser: "Bowling Green", loserScore: "5"),
    RivalryResult(year: "1989", winner: "Bowling Green", winnerScore: "27", loser: "Toledo", loserScore: "23"),
    RivalryResult(year: "1990", winner: "Toledo", winnerScore: "19", loser: "Bowling Green", loserScore: "13"),
    RivalryResult(year: "1991", winner: "Bowling Green", winnerScore: "24", loser: "Toledo", loserScore: "21"),
    RivalryResult(year: "1992", winner: "Toledo", winnerScore: "10", loser: "Bowling Green", loserScore: "9"),
    RivalryResult(year: "1993", winner: "Bowling Green", winnerScore: "17", loser: "Toledo", loserScore: "10"),
    RivalryResult(year: "1994", winner: "Toledo", winnerScore: "31", loser: "Bowling Green", loserScore: "16"),
    RivalryResult(year: "1995", winner: "Bowling Green", winnerScore: "35", loser: "Toledo", loserScore: "16"),
    RivalryResult(year: "1996", winner: "Toledo", winnerScore: "24", loser: "Bowling Green", loserScore: "16"),
    RivalryResult(year: "1997", winner: "Bowling Green", winnerScore: "35", loser: "Toledo", loserScore: "20"),
    RivalryResult(year: "1998", winner: "Toledo", winnerScore: "24", loser: "Bowling Green", loserScore: "16"),
    RivalryResult(year: "1999", winner: "Bowling Green", winnerScore: "34", loser: "Toledo", loserScore: "23"),
    RivalryResult(year: "2000", winner: "Toledo", winnerScore: "51", loser: "Bowling Green", loserScore: "17"),
    RivalryResult(year: "2001", winner: "Bowling Green", winnerScore: "56", loser: "Toledo", loserScore: "21"),
    RivalryResult(year: "2002", winner: "Toledo", winnerScore: "42", loser: "Bowling Green", loserScore: "24"),
    RivalryResult(year: "2003", winner: "Bowling Green", winnerScore: "31", loser: "Toledo", loserScore: "23"),
    RivalryResult(year: "2004", winner: "Toledo", winnerScore: "49", loser: "Bowling Green", loserScore: "41"),
    RivalryResult(year: "2005", winner: "Toledo", winnerScore: "44", loser: "Bowling Green", loserScore: "41"),
    RivalryResult(year: "2006", winner: "Toledo", winnerScore: "31", loser: "Bowling Green", loserScore: "21"),
    RivalryResult(year: "2007", winner: "Bowling Green", winnerScore: "37", loser: "Toledo", loserScore: "10"),
    RivalryResult(year: "2008", winner: "Bowling Green", winnerScore: "38", loser: "Toledo", loserScore: "10"),
    RivalryResult(year: "2009", winner: "Bowling Green", winnerScore: "38", loser: "Toledo", loserScore: "24"),
    RivalryResult(year: "2010", winner: "Toledo", winnerScore: "33", loser: "Bowling Green", loserScore: "14"),
    RivalryResult(year: "2011", winner: "Toledo", winnerScore: "28", loser: "Bowling Green", loserScore: "21"),
    RivalryResult(year: "2012", winner: "Toledo", winnerScore: "27", loser: "Bowling Green", loserScore: "15"),
    RivalryResult(year: "2013", winner: "Toledo", winnerScore: "28", loser: "Bowling Green", loserScore: "25"),
    RivalryResult(year: "2014", winner: "Toledo", winnerScore: "27", loser: "Bowling Green", loserScore: "20"),
    RivalryResult(year: "2015", winner: "Toledo", winnerScore: "44", loser: "Bowling Green", loserScore: "28"),
    RivalryResult(year: "2016", winner: "Toledo", winnerScore: "42", loser: "Bowling Green", loserScore: "35"),
    RivalryResult(year: "2017", winner: "Toledo", winnerScore: "66", loser: "Bowling Green", loserScore: "37"),
    RivalryResult(year: "2018", winner: "Toledo", winnerScore: "52", loser: "Bowling Green", loserScore: "36"),
    RivalryResult(year: "2019", winner: "Bowling Green", winnerScore: "20", loser: "Toledo", loserScore: "7"),
    RivalryResult(year: "2020", winner: "Toledo", winnerScore: "38", loser: "Bowling Green", loserScore: "3"),
    RivalryResult(year: "2021", winner: "Toledo", winnerScore: "49", loser: "Bowling Green", loserScore: "17"),
    RivalryResult(year: "2022", winner: "Bowling Green", winnerScore: "42", loser: "Toledo", loserScore: "35")
]

let michiganMACTrophyHistory = [
    MichiganMACTrophy(year: "2005", trophyWinner: "Western Michigan", records: ("WMU 2–0", "EMU 1–1", "CMU 0–2"), firstMatch: "EMU 23–20 (OT)", secondMatch: "WMU 31–24", thirdMatch: "WMU 44–36"),
    MichiganMACTrophy(year: "2006", trophyWinner: "Central Michigan", records: ("CMU 2–0", "WMU 1–1", "EMU 0–2"), firstMatch: "CMU 24–17 (OT)", secondMatch: "CMU 31–7", thirdMatch: "WMU 18–15"),
    MichiganMACTrophy(year: "2007", trophyWinner: "Eastern Michigan", records: ("EMU 2–0", "CMU 1–1", "WMU 0–2"), firstMatch: "EMU 48–45", secondMatch: "CMU 34–31", thirdMatch: "EMU 19–2"),
    MichiganMACTrophy(year: "2008", trophyWinner: "Eastern Michigan", records: ("CMU 1–1", "EMU 1–1", "WMU 1–1"), firstMatch: "EMU 56–52", secondMatch: "CMU 38–28", thirdMatch: "WMU 31–10"),
    MichiganMACTrophy(year: "2009", trophyWinner: "Central Michigan", records: ("CMU 2–0", "WMU 1–1", "EMU 0–2"), firstMatch: "CMU 56–8", secondMatch: "CMU 34–23", thirdMatch: "WMU 35–14"),
    MichiganMACTrophy(year: "2010", trophyWinner: "Central Michigan", records: ("CMU 2–0", "WMU 1–1", "EMU 0–2"), firstMatch: "CMU 52–14", secondMatch: "CMU 26–22", thirdMatch: "WMU 45–30"),
    MichiganMACTrophy(year: "2011", trophyWinner: "Eastern Michigan", records: ("EMU 2–0", "WMU 1–1", "CMU 0–2"), firstMatch: "EMU 35–28", secondMatch: "WMU 44–14", thirdMatch: "EMU 14–10"),
    MichiganMACTrophy(year: "2012", trophyWinner: "Eastern Michigan", records: ("CMU 1–1", "EMU 1–1", "WMU 1–1"), firstMatch: "CMU 34–31", secondMatch: "WMU 42–31", thirdMatch: "EMU 29–23"),
    MichiganMACTrophy(year: "2013", trophyWinner: "Central Michigan", records: ("CMU 2–0", "EMU 1–1", "WMU 0–2"), firstMatch: "CMU 42–10", secondMatch: "CMU 27–22", thirdMatch: "EMU 35–32 (OT)"),
    MichiganMACTrophy(year: "2014", trophyWinner: "Western Michigan", records: ("WMU 2–0", "CMU 1–1", "EMU 0–2"), firstMatch: "CMU 38–7", secondMatch: "WMU 32–20", thirdMatch: "WMU 51–7"),
    MichiganMACTrophy(year: "2015", trophyWinner: "Western Michigan", records: ("WMU 2–0", "CMU 1–1", "EMU 0–2"), firstMatch: "CMU 35–28", secondMatch: "WMU 41–39", thirdMatch: "WMU 58–28"),
    MichiganMACTrophy(year: "2016", trophyWinner: "Western Michigan", records: ("WMU 2–0", "EMU 1–1", "CMU 0–2"), firstMatch: "EMU 26–21", secondMatch: "WMU 49–10", thirdMatch: "WMU 45–31"),
    MichiganMACTrophy(year: "2017", trophyWinner: "Central Michigan", records: ("CMU 2–0", "WMU 1–1", "EMU 0–2"), firstMatch: "CMU 42–30", secondMatch: "CMU 35–28", thirdMatch: "WMU 20–17 (OT)"),
    MichiganMACTrophy(year: "2018", trophyWinner: "Western Michigan", records: ("WMU 2–0", "EMU 1–1", "CMU 0–2"), firstMatch: "EMU 17–7", secondMatch: "WMU 35–10", thirdMatch: "WMU 27–24"),
    MichiganMACTrophy(year: "2019", trophyWinner: "Western Michigan", records: ("CMU 1–1", "EMU 1–1", "WMU 1–1"), firstMatch: "CMU 42–16", secondMatch: "WMU 31–15", thirdMatch: "EMU 34–27"),
    MichiganMACTrophy(year: "2020", trophyWinner: "Western Michigan", records: ("CMU 1–1", "EMU 1–1", "WMU 1–1"), firstMatch: "CMU 31–23", secondMatch: "WMU 52–44", thirdMatch: "EMU 53–42"),
    MichiganMACTrophy(year: "2021", trophyWinner: "Central Michigan", records: ("CMU 2–0", "EMU 1–1", "WMU 0–2"), firstMatch: "CMU 31–10", secondMatch: "CMU 42–30", thirdMatch: "EMU 22–21"),
    MichiganMACTrophy(year: "2022", trophyWinner: "Eastern Michigan", records: ("EMU 2–0", "WMU 1–1", "CMU 0–2"), firstMatch: "EMU 38–19", secondMatch: "WMU 12–10", thirdMatch: "EMU 45–23")
]

let anniversaryAwardHistory: [RivalryResult] = [
    RivalryResult(year: "1920", winner: "Bowling Green", winnerScore: "7", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1921", winner: "Bowling Green, Kent State", winnerScore: "0", loser: "Bowling Green, Kent State", loserScore: "0"),
    RivalryResult(year: "1922", winner: "Bowling Green", winnerScore: "6", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1927", winner: "Bowling Green", winnerScore: "13", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1928", winner: "Bowling Green, Kent State", winnerScore: "6", loser: "Bowling Green, Kent State", loserScore: "6"),
    RivalryResult(year: "1934", winner: "Bowling Green, Kent State", winnerScore: "0", loser: "Bowling Green, Kent State", loserScore: "0"),
    RivalryResult(year: "1935", winner: "Kent State", winnerScore: "45", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1936", winner: "Kent State", winnerScore: "6", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1937", winner: "Bowling Green, Kent State", winnerScore: "13", loser: "Bowling Green, Kent State", loserScore: "13"),
    RivalryResult(year: "1938", winner: "Kent State", winnerScore: "7", loser: "Bowling Green", loserScore: "3"),
    RivalryResult(year: "1939", winner: "Bowling Green", winnerScore: "34", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1940", winner: "Kent State", winnerScore: "13", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1941", winner: "Bowling Green", winnerScore: "12", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1942", winner: "Kent State", winnerScore: "7", loser: "Bowling Green", loserScore: "0"),
    RivalryResult(year: "1946", winner: "Bowling Green", winnerScore: "13", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1947", winner: "Bowling Green", winnerScore: "21", loser: "Kent State", loserScore: "18"),
    RivalryResult(year: "1948", winner: "Bowling Green", winnerScore: "23", loser: "Kent State", loserScore: "14"),
    RivalryResult(year: "1949", winner: "Bowling Green", winnerScore: "27", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1950", winner: "Kent State", winnerScore: "19", loser: "Bowling Green", loserScore: "6"),
    RivalryResult(year: "1951", winner: "Bowling Green, Kent State", winnerScore: "27", loser: "Bowling Green, Kent State", loserScore: "27"),
    RivalryResult(year: "1952", winner: "Bowling Green", winnerScore: "44", loser: "Kent State", loserScore: "21"),
    RivalryResult(year: "1953", winner: "Kent State", winnerScore: "41", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1954", winner: "Kent State", winnerScore: "28", loser: "Bowling Green", loserScore: "25"),
    RivalryResult(year: "1955", winner: "Bowling Green, Kent State", winnerScore: "6", loser: "Bowling Green, Kent State", loserScore: "6"),
    RivalryResult(year: "1956", winner: "Bowling Green", winnerScore: "17", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1957", winner: "Bowling Green", winnerScore: "13", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1958", winner: "Kent State", winnerScore: "8", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1959", winner: "Bowling Green", winnerScore: "25", loser: "Kent State", loserScore: "8"),
    RivalryResult(year: "1960", winner: "Bowling Green", winnerScore: "28", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1961", winner: "Bowling Green", winnerScore: "21", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1962", winner: "Bowling Green", winnerScore: "45", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1963", winner: "Bowling Green", winnerScore: "18", loser: "Kent State", loserScore: "3"),
    RivalryResult(year: "1964", winner: "Bowling Green", winnerScore: "41", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1965", winner: "Bowling Green", winnerScore: "7", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1966", winner: "Kent State", winnerScore: "35", loser: "Bowling Green", loserScore: "12"),
    RivalryResult(year: "1967", winner: "Bowling Green", winnerScore: "7", loser: "Kent State", loserScore: "6"),
    RivalryResult(year: "1968", winner: "Bowling Green", winnerScore: "30", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1969", winner: "Bowling Green", winnerScore: "7", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1970", winner: "Bowling Green", winnerScore: "44", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "1971", winner: "Bowling Green", winnerScore: "46", loser: "Kent State", loserScore: "33"),
    RivalryResult(year: "1972", winner: "Kent State", winnerScore: "14", loser: "Bowling Green", loserScore: "10"),
    RivalryResult(year: "1973", winner: "Kent State", winnerScore: "21", loser: "Bowling Green", loserScore: "7"),
    RivalryResult(year: "1974", winner: "Bowling Green", winnerScore: "26", loser: "Kent State", loserScore: "10"),
    RivalryResult(year: "1975", winner: "Bowling Green", winnerScore: "35", loser: "Kent State", loserScore: "9"),
    RivalryResult(year: "1976", winner: "Bowling Green", winnerScore: "17", loser: "Kent State", loserScore: "13"),
    RivalryResult(year: "1977", winner: "Bowling Green", winnerScore: "14", loser: "Kent State", loserScore: "10"),
    RivalryResult(year: "1978", winner: "Bowling Green", winnerScore: "28", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "1979", winner: "Bowling Green", winnerScore: "28", loser: "Kent State", loserScore: "17"),
    RivalryResult(year: "1980", winner: "Bowling Green", winnerScore: "24", loser: "Kent State", loserScore: "3"),
    RivalryResult(year: "1981", winner: "Bowling Green", winnerScore: "13", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1982", winner: "Bowling Green", winnerScore: "41", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1983", winner: "Bowling Green", winnerScore: "38", loser: "Kent State", loserScore: "3"),
    RivalryResult(year: "1984", winner: "Bowling Green", winnerScore: "27", loser: "Kent State", loserScore: "10"),
    RivalryResult(year: "1985", winner: "Bowling Green", winnerScore: "26", loser: "Kent State", loserScore: "14"),
    RivalryResult(year: "1986", winner: "Bowling Green", winnerScore: "31", loser: "Kent State", loserScore: "15"),
    RivalryResult(year: "1987", winner: "Bowling Green", winnerScore: "30", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "1988", winner: "Kent State", winnerScore: "31", loser: "Bowling Green", loserScore: "19"),
    RivalryResult(year: "1989", winner: "Bowling Green", winnerScore: "51", loser: "Kent State", loserScore: "28"),
    RivalryResult(year: "1990", winner: "Bowling Green", winnerScore: "20", loser: "Kent State", loserScore: "16"),
    RivalryResult(year: "1991", winner: "Bowling Green", winnerScore: "35", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1992", winner: "Bowling Green", winnerScore: "28", loser: "Kent State", loserScore: "22"),
    RivalryResult(year: "1993", winner: "Bowling Green", winnerScore: "40", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "1994", winner: "Bowling Green", winnerScore: "22", loser: "Kent State", loserScore: "16"),
    RivalryResult(year: "1995", winner: "Bowling Green", winnerScore: "26", loser: "Kent State", loserScore: "15"),
    RivalryResult(year: "1996", winner: "Bowling Green", winnerScore: "31", loser: "Kent State", loserScore: "24"),
    RivalryResult(year: "1997", winner: "Kent State", winnerScore: "29", loser: "Bowling Green", loserScore: "20"),
    RivalryResult(year: "1998", winner: "Bowling Green", winnerScore: "42", loser: "Kent State", loserScore: "21"),
    RivalryResult(year: "1999", winner: "Kent State", winnerScore: "41", loser: "Bowling Green", loserScore: "27"),
    RivalryResult(year: "2000", winner: "Bowling Green", winnerScore: "18", loser: "Kent State", loserScore: "11"),
    RivalryResult(year: "2001", winner: "Bowling Green", winnerScore: "24", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "2002", winner: "Bowling Green", winnerScore: "45", loser: "Kent State", loserScore: "14"),
    RivalryResult(year: "2003", winner: "Bowling Green", winnerScore: "42", loser: "Kent State", loserScore: "33"),
    RivalryResult(year: "2005", winner: "Bowling Green", winnerScore: "24", loser: "Kent State", loserScore: "14"),
    RivalryResult(year: "2006", winner: "Kent State", winnerScore: "38", loser: "Bowling Green", loserScore: "3"),
    RivalryResult(year: "2007", winner: "Bowling Green", winnerScore: "31", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "2008", winner: "Bowling Green", winnerScore: "45", loser: "Kent State", loserScore: "30"),
    RivalryResult(year: "2009", winner: "Bowling Green", winnerScore: "36", loser: "Kent State", loserScore: "35"),
    RivalryResult(year: "2010", winner: "Kent State", winnerScore: "30", loser: "Bowling Green", loserScore: "6"),
    RivalryResult(year: "2011", winner: "Kent State", winnerScore: "27", loser: "Bowling Green", loserScore: "15"),
    RivalryResult(year: "2012", winner: "Kent State", winnerScore: "31", loser: "Bowling Green", loserScore: "24"),
    RivalryResult(year: "2013", winner: "Bowling Green", winnerScore: "41", loser: "Kent State", loserScore: "22"),
    RivalryResult(year: "2014", winner: "Bowling Green", winnerScore: "30", loser: "Kent State", loserScore: "20"),
    RivalryResult(year: "2015", winner: "Bowling Green", winnerScore: "48", loser: "Kent State", loserScore: "0"),
    RivalryResult(year: "2016", winner: "Bowling Green", winnerScore: "42", loser: "Kent State", loserScore: "7"),
    RivalryResult(year: "2017", winner: "Bowling Green", winnerScore: "44", loser: "Kent State", loserScore: "16"),
    RivalryResult(year: "2018", winner: "Kent State", winnerScore: "35", loser: "Bowling Green", loserScore: "28"),
    RivalryResult(year: "2019", winner: "Kent State", winnerScore: "62", loser: "Bowling Green", loserScore: "20"),
    RivalryResult(year: "2020", winner: "Kent State", winnerScore: "62", loser: "Bowling Green", loserScore: "24"),
    RivalryResult(year: "2021", winner: "Kent State", winnerScore: "27", loser: "Bowling Green", loserScore: "20"),
    RivalryResult(year: "2022", winner: "Kent State", winnerScore: "40", loser: "Bowling Green", loserScore: "6")
]
    
let bronzeStalkHistory: [RivalryResult] = [
    RivalryResult(year: "1941", winner: "Ball State, Northern Illinois", winnerScore: "6", loser: "Ball State, Northern Illinois", loserScore: "6"),
    RivalryResult(year: "1942", winner: "Ball State", winnerScore: "14", loser: "Northern Illinois", loserScore: "0"),
    RivalryResult(year: "1966", winner: "Northern Illinois", winnerScore: "38", loser: "Ball State", loserScore: "24"),
    RivalryResult(year: "1967", winner: "Northern Illinois", winnerScore: "28", loser: "Ball State", loserScore: "14"),
    RivalryResult(year: "1968", winner: "Northern Illinois", winnerScore: "40", loser: "Ball State", loserScore: "20"),
    RivalryResult(year: "1969", winner: "Northern Illinois", winnerScore: "17", loser: "Ball State", loserScore: "13"),
    RivalryResult(year: "1970", winner: "Northern Illinois", winnerScore: "31", loser: "Ball State", loserScore: "14"),
    RivalryResult(year: "1971", winner: "Ball State, Northern Illinois", winnerScore: "10", loser: "Ball State, Northern Illinois", loserScore: "10"),
    RivalryResult(year: "1973", winner: "Northern Illinois", winnerScore: "45", loser: "Ball State", loserScore: "17"),
    RivalryResult(year: "1974", winner: "Ball State", winnerScore: "31", loser: "Northern Illinois", loserScore: "21"),
    RivalryResult(year: "1978", winner: "Ball State", winnerScore: "31", loser: "Northern Illinois", loserScore: "13"),
    RivalryResult(year: "1979", winner: "Ball State", winnerScore: "42", loser: "Northern Illinois", loserScore: "0"),
    RivalryResult(year: "1980", winner: "Ball State", winnerScore: "18", loser: "Northern Illinois", loserScore: "17"),
    RivalryResult(year: "1981", winner: "Ball State", winnerScore: "23", loser: "Northern Illinois", loserScore: "0"),
    RivalryResult(year: "1982", winner: "Ball State", winnerScore: "14", loser: "Northern Illinois", loserScore: "7"),
    RivalryResult(year: "1983", winner: "Northern Illinois", winnerScore: "27", loser: "Ball State", loserScore: "14"),
    RivalryResult(year: "1984", winner: "Ball State", winnerScore: "15", loser: "Northern Illinois", loserScore: "14"),
    RivalryResult(year: "1985", winner: "Ball State", winnerScore: "29", loser: "Northern Illinois", loserScore: "0"),
    RivalryResult(year: "1986", winner: "Ball State", winnerScore: "20", loser: "Northern Illinois", loserScore: "10"),
    RivalryResult(year: "1987", winner: "Ball State", winnerScore: "42", loser: "Northern Illinois", loserScore: "17"),
    RivalryResult(year: "1988", winner: "Ball State", winnerScore: "18", loser: "Northern Illinois", loserScore: "17"),
    RivalryResult(year: "1997", winner: "Ball State", winnerScore: "21", loser: "Northern Illinois", loserScore: "14"),
    RivalryResult(year: "1998", winner: "Ball State", winnerScore: "18", loser: "Northern Illinois", loserScore: "13"),
    RivalryResult(year: "1999", winner: "Northern Illinois", winnerScore: "37", loser: "Ball State", loserScore: "17"),
    RivalryResult(year: "2000", winner: "Northern Illinois", winnerScore: "43", loser: "Ball State", loserScore: "14"),
    RivalryResult(year: "2001", winner: "Northern Illinois", winnerScore: "33", loser: "Ball State", loserScore: "29"),
    RivalryResult(year: "2002", winner: "Northern Illinois", winnerScore: "41", loser: "Ball State", loserScore: "29"),
    RivalryResult(year: "2003", winner: "Northern Illinois", winnerScore: "48", loser: "Ball State", loserScore: "23"),
    RivalryResult(year: "2004", winner: "Northern Illinois", winnerScore: "38", loser: "Ball State", loserScore: "31"),
    RivalryResult(year: "2005", winner: "Ball State", winnerScore: "31", loser: "Northern Illinois", loserScore: "17"),
    RivalryResult(year: "2006", winner: "Northern Illinois", winnerScore: "40", loser: "Ball State", loserScore: "28"),
    RivalryResult(year: "2007", winner: "Ball State", winnerScore: "27", loser: "Northern Illinois", loserScore: "21"),
    RivalryResult(year: "2008", winner: "Ball State", winnerScore: "45", loser: "Northern Illinois", loserScore: "14"),
    RivalryResult(year: "2009", winner: "Northern Illinois", winnerScore: "26", loser: "Ball State", loserScore: "20"),
    RivalryResult(year: "2010", winner: "Northern Illinois", winnerScore: "59", loser: "Ball State", loserScore: "21"),
    RivalryResult(year: "2011", winner: "Northern Illinois", winnerScore: "41", loser: "Ball State", loserScore: "38"),
    RivalryResult(year: "2012", winner: "Northern Illinois", winnerScore: "35", loser: "Ball State", loserScore: "23"),
    RivalryResult(year: "2013", winner: "Northern Illinois", winnerScore: "48", loser: "Ball State", loserScore: "27"),
    RivalryResult(year: "2014", winner: "Northern Illinois", winnerScore: "35", loser: "Ball State", loserScore: "21"),
    RivalryResult(year: "2015", winner: "Northern Illinois", winnerScore: "59", loser: "Ball State", loserScore: "41"),
    RivalryResult(year: "2016", winner: "Northern Illinois", winnerScore: "31", loser: "Ball State", loserScore: "24"),
    RivalryResult(year: "2017", winner: "Northern Illinois", winnerScore: "63", loser: "Ball State", loserScore: "17"),
    RivalryResult(year: "2018", winner: "Northern Illinois", winnerScore: "24", loser: "Ball State", loserScore: "16"),
    RivalryResult(year: "2019", winner: "Ball State", winnerScore: "27", loser: "Northern Illinois", loserScore: "20"),
    RivalryResult(year: "2020", winner: "Ball State", winnerScore: "31", loser: "Northern Illinois", loserScore: "25"),
    RivalryResult(year: "2021", winner: "Northern Illinois", winnerScore: "30", loser: "Ball State", loserScore: "29"),
    RivalryResult(year: "2022", winner: "Ball State", winnerScore: "44", loser: "Northern Illinois", loserScore: "38")
    ]

let victoryCannonHistory: [RivalryResult] = [
    RivalryResult(year: "1907", winner: "Western Michigan", winnerScore: "29", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1908", winner: "Western Michigan", winnerScore: "11", loser: "Central Michigan", loserScore: "5"),
    RivalryResult(year: "1909", winner: "Western Michigan", winnerScore: "11", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1910", winner: "Western Michigan", winnerScore: "16", loser: "Central Michigan", loserScore: "6"),
    RivalryResult(year: "1925", winner: "Western Michigan, Central Michigan", winnerScore: "0", loser: "Western Michigan, Central Michigan", loserScore: "0"),
    RivalryResult(year: "1927", winner: "Central Michigan", winnerScore: "18", loser: "Western Michigan", loserScore: "12"),
    RivalryResult(year: "1928", winner: "Western Michigan", winnerScore: "19", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1929", winner: "Western Michigan", winnerScore: "25", loser: "Central Michigan", loserScore: "6"),
    RivalryResult(year: "1930", winner: "Western Michigan", winnerScore: "54", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1931", winner: "Western Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "6"),
    RivalryResult(year: "1932", winner: "Western Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1933", winner: "Western Michigan", winnerScore: "19", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1934", winner: "Western Michigan", winnerScore: "13", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1935", winner: "Western Michigan", winnerScore: "13", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1936", winner: "Western Michigan", winnerScore: "33", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1937", winner: "Western Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1938", winner: "Western Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1943", winner: "Western Michigan", winnerScore: "19", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1944", winner: "Western Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "14"),
    RivalryResult(year: "1945", winner: "Central Michigan", winnerScore: "6", loser: "Western Michigan", loserScore: "0"),
    RivalryResult(year: "1946", winner: "Western Michigan", winnerScore: "27", loser: "Central Michigan", loserScore: "21"),
    RivalryResult(year: "1947", winner: "Western Michigan", winnerScore: "20", loser: "Central Michigan", loserScore: "12"),
    RivalryResult(year: "1948", winner: "Western Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1949", winner: "Western Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "8"),
    RivalryResult(year: "1950", winner: "Western Michigan", winnerScore: "21", loser: "Central Michigan", loserScore: "13"),
    RivalryResult(year: "1951", winner: "Western Michigan", winnerScore: "46", loser: "Central Michigan", loserScore: "25"),
    RivalryResult(year: "1952", winner: "Western Michigan", winnerScore: "18", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1953", winner: "Central Michigan", winnerScore: "21", loser: "Western Michigan", loserScore: "0"),
    RivalryResult(year: "1954", winner: "Central Michigan", winnerScore: "25", loser: "Western Michigan", loserScore: "19"),
    RivalryResult(year: "1955", winner: "Central Michigan", winnerScore: "27", loser: "Western Michigan", loserScore: "12"),
    RivalryResult(year: "1956", winner: "Central Michigan", winnerScore: "14", loser: "Western Michigan", loserScore: "7"),
    RivalryResult(year: "1957", winner: "Western Michigan", winnerScore: "33", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1958", winner: "Central Michigan", winnerScore: "33", loser: "Western Michigan", loserScore: "32"),
    RivalryResult(year: "1959", winner: "Central Michigan", winnerScore: "21", loser: "Western Michigan", loserScore: "15"),
    RivalryResult(year: "1960", winner: "Western Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1961", winner: "Western Michigan", winnerScore: "27", loser: "Central Michigan", loserScore: "21"),
    RivalryResult(year: "1962", winner: "Western Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1963", winner: "Central Michigan", winnerScore: "30", loser: "Western Michigan", loserScore: "14"),
    RivalryResult(year: "1964", winner: "Central Michigan", winnerScore: "18", loser: "Western Michigan", loserScore: "6"),
    RivalryResult(year: "1965", winner: "Western Michigan", winnerScore: "21", loser: "Central Michigan", loserScore: "13"),
    RivalryResult(year: "1966", winner: "Western Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "14"),
    RivalryResult(year: "1969", winner: "Western Michigan", winnerScore: "24", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1970", winner: "Western Michigan", winnerScore: "41", loser: "Central Michigan", loserScore: "0"),
    RivalryResult(year: "1971", winner: "Western Michigan", winnerScore: "10", loser: "Central Michigan", loserScore: "7"),
    RivalryResult(year: "1972", winner: "Western Michigan", winnerScore: "14", loser: "Central Michigan", loserScore: "10"),
    RivalryResult(year: "1973", winner: "Western Michigan", winnerScore: "18", loser: "Central Michigan", loserScore: "13"),
    RivalryResult(year: "1974", winner: "Central Michigan", winnerScore: "42", loser: "Western Michigan", loserScore: "6"),
    RivalryResult(year: "1975", winner: "Central Michigan", winnerScore: "34", loser: "Western Michigan", loserScore: "0"),
    RivalryResult(year: "1976", winner: "Western Michigan", winnerScore: "42", loser: "Central Michigan", loserScore: "14"),
    RivalryResult(year: "1977", winner: "Central Michigan", winnerScore: "28", loser: "Western Michigan", loserScore: "23"),
    RivalryResult(year: "1978", winner: "Central Michigan", winnerScore: "35", loser: "Western Michigan", loserScore: "14"),
    RivalryResult(year: "1979", winner: "Central Michigan", winnerScore: "10", loser: "Western Michigan", loserScore: "0"),
    RivalryResult(year: "1980", winner: "Central Michigan", winnerScore: "22", loser: "Western Michigan", loserScore: "10"),
    RivalryResult(year: "1981", winner: "Central Michigan", winnerScore: "15", loser: "Western Michigan", loserScore: "13"),
    RivalryResult(year: "1982", winner: "Western Michigan, Central Michigan", winnerScore: "18", loser: "Western Michigan, Central Michigan", loserScore: "18"),
    RivalryResult(year: "1983", winner: "Central Michigan", winnerScore: "32", loser: "Western Michigan", loserScore: "14"),
    RivalryResult(year: "1984", winner: "Central Michigan", winnerScore: "38", loser: "Western Michigan", loserScore: "19"),
    RivalryResult(year: "1985", winner: "Central Michigan", winnerScore: "24", loser: "Western Michigan", loserScore: "17"),
    RivalryResult(year: "1986", winner: "Central Michigan", winnerScore: "18", loser: "Western Michigan", loserScore: "10"),
    RivalryResult(year: "1987", winner: "Central Michigan", winnerScore: "30", loser: "Western Michigan", loserScore: "27"),
    RivalryResult(year: "1988", winner: "Western Michigan", winnerScore: "42", loser: "Central Michigan", loserScore: "24"),
    RivalryResult(year: "1989", winner: "Central Michigan", winnerScore: "34", loser: "Western Michigan", loserScore: "6"),
    RivalryResult(year: "1990", winner: "Central Michigan", winnerScore: "20", loser: "Western Michigan", loserScore: "13"),
    RivalryResult(year: "1991", winner: "Central Michigan", winnerScore: "27", loser: "Western Michigan", loserScore: "17"),
    RivalryResult(year: "1992", winner: "Western Michigan", winnerScore: "19", loser: "Central Michigan", loserScore: "14"),
    RivalryResult(year: "1993", winner: "Central Michigan", winnerScore: "23", loser: "Western Michigan", loserScore: "18"),
    RivalryResult(year: "1994", winner: "Central Michigan", winnerScore: "35", loser: "Western Michigan", loserScore: "28"),
    RivalryResult(year: "1995", winner: "Western Michigan", winnerScore: "48", loser: "Central Michigan", loserScore: "31"),
    RivalryResult(year: "1996", winner: "Central Michigan", winnerScore: "38", loser: "Western Michigan", loserScore: "28"),
    RivalryResult(year: "1997", winner: "Western Michigan", winnerScore: "38", loser: "Central Michigan", loserScore: "24"),
    RivalryResult(year: "1998", winner: "Central Michigan", winnerScore: "26", loser: "Western Michigan", loserScore: "24"),
    RivalryResult(year: "1999", winner: "Western Michigan", winnerScore: "38", loser: "Central Michigan", loserScore: "16"),
    RivalryResult(year: "2000", winner: "Central Michigan", winnerScore: "21", loser: "Western Michigan", loserScore: "17"),
    RivalryResult(year: "2001", winner: "Western Michigan", winnerScore: "20", loser: "Central Michigan", loserScore: "17"),
    RivalryResult(year: "2002", winner: "Western Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "10"),
    RivalryResult(year: "2003", winner: "Western Michigan", winnerScore: "44", loser: "Central Michigan", loserScore: "21"),
    RivalryResult(year: "2004", winner: "Central Michigan", winnerScore: "24", loser: "Western Michigan", loserScore: "21"),
    RivalryResult(year: "2005", winner: "Western Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "24"),
    RivalryResult(year: "2006", winner: "Central Michigan", winnerScore: "31", loser: "Western Michigan", loserScore: "7"),
    RivalryResult(year: "2007", winner: "Central Michigan", winnerScore: "34", loser: "Western Michigan", loserScore: "31"),
    RivalryResult(year: "2008", winner: "Central Michigan", winnerScore: "38", loser: "Western Michigan", loserScore: "28"),
    RivalryResult(year: "2009", winner: "Central Michigan", winnerScore: "34", loser: "Western Michigan", loserScore: "23"),
    RivalryResult(year: "2010", winner: "Central Michigan", winnerScore: "26", loser: "Western Michigan", loserScore: "22"),
    RivalryResult(year: "2011", winner: "Western Michigan", winnerScore: "44", loser: "Central Michigan", loserScore: "14"),
    RivalryResult(year: "2012", winner: "Western Michigan", winnerScore: "42", loser: "Central Michigan", loserScore: "31"),
    RivalryResult(year: "2013", winner: "Central Michigan", winnerScore: "27", loser: "Western Michigan", loserScore: "22"),
    RivalryResult(year: "2014", winner: "Western Michigan", winnerScore: "32", loser: "Central Michigan", loserScore: "20"),
    RivalryResult(year: "2015", winner: "Western Michigan", winnerScore: "41", loser: "Central Michigan", loserScore: "39"),
    RivalryResult(year: "2016", winner: "Western Michigan", winnerScore: "49", loser: "Central Michigan", loserScore: "10"),
    RivalryResult(year: "2017", winner: "Central Michigan", winnerScore: "35", loser: "Western Michigan", loserScore: "28"),
    RivalryResult(year: "2018", winner: "Western Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "10"),
    RivalryResult(year: "2019", winner: "Western Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "15"),
    RivalryResult(year: "2020", winner: "Western Michigan", winnerScore: "52", loser: "Central Michigan", loserScore: "44"),
    RivalryResult(year: "2021", winner: "Central Michigan", winnerScore: "42", loser: "Western Michigan", loserScore: "30"),
    RivalryResult(year: "2022", winner: "Western Michigan", winnerScore: "12", loser: "Central Michigan", loserScore: "10")
]

let CMUEMUHistory: [RivalryResult] = [
        RivalryResult(year: "1902", winner: "Central Michigan", winnerScore: "10", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1905", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1907", winner: "Eastern Michigan", winnerScore: "38", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1908", winner: "Central Michigan", winnerScore: "11", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1909", winner: "Eastern Michigan", winnerScore: "17", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1910", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1912", winner: "Central Michigan, Eastern Michigan", winnerScore: "0", loser: "Central Michigan, Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1917", winner: "Eastern Michigan", winnerScore: "63", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1919", winner: "Central Michigan, Eastern Michigan", winnerScore: "7", loser: "Central Michigan, Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1920", winner: "Eastern Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "6"),
        RivalryResult(year: "1921", winner: "Eastern Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "6"),
        RivalryResult(year: "1922", winner: "Central Michigan, Eastern Michigan", winnerScore: "0", loser: "Central Michigan, Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1923", winner: "Central Michigan", winnerScore: "27", loser: "Eastern Michigan", loserScore: "3"),
        RivalryResult(year: "1924", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1926", winner: "Eastern Michigan", winnerScore: "41", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1927", winner: "Eastern Michigan", winnerScore: "6", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1928", winner: "Eastern Michigan", winnerScore: "36", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1929", winner: "Eastern Michigan", winnerScore: "24", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1930", winner: "Eastern Michigan", winnerScore: "13", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1931", winner: "Central Michigan", winnerScore: "20", loser: "Eastern Michigan", loserScore: "12"),
        RivalryResult(year: "1932", winner: "Eastern Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1933", winner: "Eastern Michigan", winnerScore: "13", loser: "Central Michigan", loserScore: "7"),
        RivalryResult(year: "1934", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "12"),
        RivalryResult(year: "1935", winner: "Eastern Michigan", winnerScore: "7", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1936", winner: "Eastern Michigan", winnerScore: "13", loser: "Central Michigan", loserScore: "7"),
        RivalryResult(year: "1937", winner: "Central Michigan", winnerScore: "27", loser: "Eastern Michigan", loserScore: "10"),
        RivalryResult(year: "1938", winner: "Central Michigan", winnerScore: "7", loser: "Eastern Michigan", loserScore: "6"),
        RivalryResult(year: "1939", winner: "Central Michigan", winnerScore: "14", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1940", winner: "Central Michigan", winnerScore: "24", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1941", winner: "Central Michigan", winnerScore: "12", loser: "Eastern Michigan", loserScore: "6"),
        RivalryResult(year: "1942", winner: "Central Michigan", winnerScore: "14", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1946", winner: "Central Michigan", winnerScore: "26", loser: "Eastern Michigan", loserScore: "13"),
        RivalryResult(year: "1947", winner: "Central Michigan", winnerScore: "33", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1948", winner: "Eastern Michigan", winnerScore: "6", loser: "Central Michigan", loserScore: "0"),
        RivalryResult(year: "1949", winner: "Central Michigan", winnerScore: "18", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1950", winner: "Central Michigan", winnerScore: "26", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1951", winner: "Central Michigan", winnerScore: "19", loser: "Eastern Michigan", loserScore: "13"),
        RivalryResult(year: "1952", winner: "Central Michigan", winnerScore: "26", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1953", winner: "Central Michigan, Eastern Michigan", winnerScore: "33", loser: "Central Michigan, Eastern Michigan", loserScore: "33"),
        RivalryResult(year: "1954", winner: "Central Michigan", winnerScore: "28", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1955", winner: "Central Michigan", winnerScore: "27", loser: "Eastern Michigan", loserScore: "20"),
        RivalryResult(year: "1956", winner: "Central Michigan", winnerScore: "19", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1957", winner: "Eastern Michigan", winnerScore: "39", loser: "Central Michigan", loserScore: "6"),
        RivalryResult(year: "1958", winner: "Central Michigan", winnerScore: "7", loser: "Eastern Michigan", loserScore: "6"),
        RivalryResult(year: "1959", winner: "Central Michigan", winnerScore: "21", loser: "Eastern Michigan", loserScore: "8"),
        RivalryResult(year: "1960", winner: "Central Michigan", winnerScore: "28", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1961", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "11"),
        RivalryResult(year: "1962", winner: "Central Michigan", winnerScore: "24", loser: "Eastern Michigan", loserScore: "0"),
        RivalryResult(year: "1963", winner: "Central Michigan", winnerScore: "55", loser: "Eastern Michigan", loserScore: "20"),
        RivalryResult(year: "1972", winner: "Eastern Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "3"),
        RivalryResult(year: "1973", winner: "Central Michigan", winnerScore: "31", loser: "Eastern Michigan", loserScore: "21"),
        RivalryResult(year: "1974", winner: "Central Michigan", winnerScore: "28", loser: "Eastern Michigan", loserScore: "13"),
        RivalryResult(year: "1975", winner: "Central Michigan", winnerScore: "20", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "1976", winner: "Eastern Michigan", winnerScore: "30", loser: "Central Michigan", loserScore: "27"),
        RivalryResult(year: "1977", winner: "Central Michigan", winnerScore: "9", loser: "Eastern Michigan", loserScore: "3"),
        RivalryResult(year: "1978", winner: "Central Michigan", winnerScore: "41", loser: "Eastern Michigan", loserScore: "9"),
        RivalryResult(year: "1979", winner: "Central Michigan", winnerScore: "37", loser: "Eastern Michigan", loserScore: "14"),
        RivalryResult(year: "1980", winner: "Central Michigan", winnerScore: "51", loser: "Eastern Michigan", loserScore: "15"),
        RivalryResult(year: "1981", winner: "Central Michigan", winnerScore: "63", loser: "Eastern Michigan", loserScore: "14"),
        RivalryResult(year: "1982", winner: "Central Michigan", winnerScore: "13", loser: "Eastern Michigan", loserScore: "8"),
        RivalryResult(year: "1983", winner: "Central Michigan", winnerScore: "24", loser: "Eastern Michigan", loserScore: "3"),
        RivalryResult(year: "1984", winner: "Central Michigan, Eastern Michigan", winnerScore: "16", loser: "Central Michigan, Eastern Michigan", loserScore: "16"),
        RivalryResult(year: "1985", winner: "Central Michigan", winnerScore: "17", loser: "Eastern Michigan", loserScore: "10"),
        RivalryResult(year: "1986", winner: "Eastern Michigan", winnerScore: "34", loser: "Central Michigan", loserScore: "16"),
        RivalryResult(year: "1987", winner: "Central Michigan", winnerScore: "16", loser: "Eastern Michigan", loserScore: "6"),
        RivalryResult(year: "1988", winner: "Central Michigan", winnerScore: "20", loser: "Eastern Michigan", loserScore: "6"),
        RivalryResult(year: "1989", winner: "Central Michigan", winnerScore: "24", loser: "Eastern Michigan", loserScore: "9"),
        RivalryResult(year: "1990", winner: "Central Michigan", winnerScore: "16", loser: "Eastern Michigan", loserScore: "12"),
        RivalryResult(year: "1991", winner: "Central Michigan, Eastern Michigan", winnerScore: "14", loser: "Central Michigan, Eastern Michigan", loserScore: "14"),
        RivalryResult(year: "1992", winner: "Central Michigan", winnerScore: "30", loser: "Eastern Michigan", loserScore: "13"),
        RivalryResult(year: "1993", winner: "Eastern Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "21"),
        RivalryResult(year: "1994", winner: "Central Michigan", winnerScore: "30", loser: "Eastern Michigan", loserScore: "29"),
        RivalryResult(year: "1995", winner: "Eastern Michigan", winnerScore: "34", loser: "Central Michigan", loserScore: "24"),
        RivalryResult(year: "1996", winner: "Central Michigan", winnerScore: "41", loser: "Eastern Michigan", loserScore: "36"),
        RivalryResult(year: "1997", winner: "Eastern Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "24"),
        RivalryResult(year: "1998", winner: "Central Michigan", winnerScore: "36", loser: "Eastern Michigan", loserScore: "23"),
        RivalryResult(year: "1999", winner: "Central Michigan", winnerScore: "29", loser: "Eastern Michigan", loserScore: "26"),
        RivalryResult(year: "2000", winner: "Eastern Michigan", winnerScore: "31", loser: "Central Michigan", loserScore: "15"),
        RivalryResult(year: "2001", winner: "Central Michigan", winnerScore: "35", loser: "Eastern Michigan", loserScore: "30"),
        RivalryResult(year: "2002", winner: "Central Michigan", winnerScore: "47", loser: "Eastern Michigan", loserScore: "21"),
        RivalryResult(year: "2003", winner: "Central Michigan", winnerScore: "38", loser: "Eastern Michigan", loserScore: "10"),
        RivalryResult(year: "2004", winner: "Eastern Michigan", winnerScore: "61", loser: "Central Michigan", loserScore: "58"),
        RivalryResult(year: "2005", winner: "Eastern Michigan", winnerScore: "23", loser: "Central Michigan", loserScore: "20"),
        RivalryResult(year: "2006", winner: "Central Michigan", winnerScore: "24", loser: "Eastern Michigan", loserScore: "17"),
        RivalryResult(year: "2007", winner: "Eastern Michigan", winnerScore: "48", loser: "Central Michigan", loserScore: "45"),
        RivalryResult(year: "2008", winner: "Eastern Michigan", winnerScore: "56", loser: "Central Michigan", loserScore: "52"),
        RivalryResult(year: "2009", winner: "Central Michigan", winnerScore: "56", loser: "Eastern Michigan", loserScore: "8"),
        RivalryResult(year: "2010", winner: "Central Michigan", winnerScore: "52", loser: "Eastern Michigan", loserScore: "14"),
        RivalryResult(year: "2011", winner: "Eastern Michigan", winnerScore: "35", loser: "Central Michigan", loserScore: "28"),
        RivalryResult(year: "2012", winner: "Central Michigan", winnerScore: "34", loser: "Eastern Michigan", loserScore: "31"),
        RivalryResult(year: "2013", winner: "Eastern Michigan", winnerScore: "42", loser: "Central Michigan", loserScore: "28"),
        RivalryResult(year: "2014", winner: "Central Michigan", winnerScore: "38", loser: "Eastern Michigan", loserScore: "7"),
        RivalryResult(year: "2015", winner: "Eastern Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "20"),
        RivalryResult(year: "2016", winner: "Central Michigan", winnerScore: "42", loser: "Eastern Michigan", loserScore: "30"),
        RivalryResult(year: "2017", winner: "Eastern Michigan", winnerScore: "28", loser: "Central Michigan", loserScore: "24"),
        RivalryResult(year: "2018", winner: "Central Michigan", winnerScore: "26", loser: "Eastern Michigan", loserScore: "23"),
        RivalryResult(year: "2019", winner: "Eastern Michigan", winnerScore: "45", loser: "Central Michigan", loserScore: "44"),
        RivalryResult(year: "2020", winner: "Central Michigan", winnerScore: "30", loser: "Eastern Michigan", loserScore: "27"),
        RivalryResult(year: "2021", winner: "Eastern Michigan", winnerScore: "37", loser: "Central Michigan", loserScore: "34"),
        RivalryResult(year: "2022", winner: "Central Michigan", winnerScore: "48", loser: "Eastern Michigan", loserScore: "24")
    ]

let redBirdRivalryHistory: [RivalryResult] = [
    RivalryResult(year: "2016", winner: "Miami", winnerScore: "31", loser: "Ball State", loserScore: "7"),
        RivalryResult(year: "2018", winner: "Miami", winnerScore: "24", loser: "Ball State", loserScore: "14"),
        RivalryResult(year: "2020", winner: "Miami", winnerScore: "44", loser: "Ball State", loserScore: "35"),
        RivalryResult(year: "2021", winner: "Ball State", winnerScore: "24", loser: "Miami", loserScore: "20"),
        RivalryResult(year: "2023", winner: "Ball State", winnerScore: "16", loser: "Miami", loserScore: "7")
]

let battleOfTheBricksHistory: [RivalryResult] = [
    RivalryResult(year: "1908", winner: "Miami", winnerScore: "5", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1909", winner: "Miami", winnerScore: "45", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1912", winner: "Miami", winnerScore: "18", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1913", winner: "Miami", winnerScore: "44", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1914", winner: "Ohio", winnerScore: "6", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1915", winner: "Miami", winnerScore: "13", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1928", winner: "Miami", winnerScore: "20", loser: "Ohio", loserScore: "13"),
    RivalryResult(year: "1929", winner: "Ohio", winnerScore: "14", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1930", winner: "Ohio", winnerScore: "27", loser: "Miami", loserScore: "6"),
    RivalryResult(year: "1931", winner: "Ohio", winnerScore: "13", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1932", winner: "Miami", winnerScore: "16", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1933", winner: "Ohio", winnerScore: "6", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1934", winner: "Miami", winnerScore: "7", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1935", winner: "Ohio", winnerScore: "20", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1936", winner: "Miami", winnerScore: "3", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1937", winner: "Ohio", winnerScore: "19", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1938", winner: "Ohio", winnerScore: "20", loser: "Miami", loserScore: "12"),
    RivalryResult(year: "1939", winner: "Ohio", winnerScore: "20", loser: "Miami", loserScore: "7"),
    RivalryResult(year: "1940", winner: "Ohio", winnerScore: "27", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1941", winner: "Ohio", winnerScore: "26", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1942", winner: "Ohio", winnerScore: "39", loser: "Miami", loserScore: "13"),
    RivalryResult(year: "1945", winner: "Miami", winnerScore: "34", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1946", winner: "Miami", winnerScore: "23", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "1947", winner: "Miami", winnerScore: "21", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1948", winner: "Miami", winnerScore: "21", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1949", winner: "Miami", winnerScore: "26", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1950", winner: "Miami", winnerScore: "28", loser: "Ohio", loserScore: "20"),
    RivalryResult(year: "1951", winner: "Miami", winnerScore: "7", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1952", winner: "Miami", winnerScore: "20", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1953", winner: "Miami, Ohio", winnerScore: "7", loser: "Miami, Ohio", loserScore: "7"),
    RivalryResult(year: "1954", winner: "Miami", winnerScore: "46", loser: "Ohio", loserScore: "13"),
    RivalryResult(year: "1955", winner: "Miami", winnerScore: "34", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1956", winner: "Miami", winnerScore: "16", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1957", winner: "Miami", winnerScore: "26", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1958", winner: "Miami", winnerScore: "14", loser: "Ohio", loserScore: "10"),
    RivalryResult(year: "1959", winner: "Miami", winnerScore: "24", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1960", winner: "Ohio", winnerScore: "21", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1961", winner: "Ohio", winnerScore: "28", loser: "Miami", loserScore: "18"),
    RivalryResult(year: "1962", winner: "Ohio", winnerScore: "12", loser: "Miami", loserScore: "6"),
    RivalryResult(year: "1963", winner: "Ohio", winnerScore: "13", loser: "Miami", loserScore: "10"),
    RivalryResult(year: "1964", winner: "Ohio", winnerScore: "10", loser: "Miami", loserScore: "7"),
    RivalryResult(year: "1965", winner: "Miami", winnerScore: "34", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1966", winner: "Miami", winnerScore: "33", loser: "Ohio", loserScore: "13"),
    RivalryResult(year: "1967", winner: "Miami", winnerScore: "22", loser: "Ohio", loserScore: "15"),
    RivalryResult(year: "1968", winner: "Ohio", winnerScore: "24", loser: "Miami", loserScore: "7"),
    RivalryResult(year: "1969", winner: "Miami", winnerScore: "24", loser: "Ohio", loserScore: "21"),
    RivalryResult(year: "1970", winner: "Ohio", winnerScore: "23", loser: "Miami", loserScore: "22"),
    RivalryResult(year: "1971", winner: "Ohio", winnerScore: "3", loser: "Miami", loserScore: "0"),
    RivalryResult(year: "1972", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1973", winner: "Miami", winnerScore: "10", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1974", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "3"),
    RivalryResult(year: "1975", winner: "Miami", winnerScore: "41", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "1976", winner: "Miami", winnerScore: "28", loser: "Ohio", loserScore: "3"),
    RivalryResult(year: "1977", winner: "Ohio", winnerScore: "28", loser: "Miami", loserScore: "3"),
    RivalryResult(year: "1978", winner: "Miami", winnerScore: "21", loser: "Ohio", loserScore: "10"),
    RivalryResult(year: "1979", winner: "Miami", winnerScore: "30", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1980", winner: "Miami", winnerScore: "28", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1981", winner: "Miami", winnerScore: "35", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "1982", winner: "Miami", winnerScore: "27", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1983", winner: "Ohio", winnerScore: "27", loser: "Miami", loserScore: "20"),
    RivalryResult(year: "1984", winner: "Miami", winnerScore: "34", loser: "Ohio", loserScore: "3"),
    RivalryResult(year: "1985", winner: "Miami", winnerScore: "24", loser: "Ohio", loserScore: "10"),
    RivalryResult(year: "1986", winner: "Miami", winnerScore: "38", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1987", winner: "Miami", winnerScore: "37", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1988", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1989", winner: "Miami", winnerScore: "42", loser: "Ohio", loserScore: "6"),
    RivalryResult(year: "1990", winner: "Miami", winnerScore: "37", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1991", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1992", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1993", winner: "Miami", winnerScore: "49", loser: "Ohio", loserScore: "0"),
    RivalryResult(year: "1994", winner: "Miami", winnerScore: "38", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "1995", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "10"),
    RivalryResult(year: "1996", winner: "Miami", winnerScore: "17", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "1997", winner: "Miami", winnerScore: "31", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "1998", winner: "Miami", winnerScore: "24", loser: "Ohio", loserScore: "3"),
    RivalryResult(year: "1999", winner: "Ohio", winnerScore: "34", loser: "Miami", loserScore: "16"),
    RivalryResult(year: "2000", winner: "Miami", winnerScore: "27", loser: "Ohio", loserScore: "13"),
    RivalryResult(year: "2001", winner: "Miami", winnerScore: "30", loser: "Ohio", loserScore: "7"),
    RivalryResult(year: "2002", winner: "Ohio", winnerScore: "21", loser: "Miami", loserScore: "14"),
    RivalryResult(year: "2003", winner: "Miami", winnerScore: "49", loser: "Ohio", loserScore: "31"),
    RivalryResult(year: "2004", winner: "Miami", winnerScore: "40", loser: "Ohio", loserScore: "20"),
    RivalryResult(year: "2005", winner: "Miami", winnerScore: "38", loser: "Ohio", loserScore: "14"),
    RivalryResult(year: "2006", winner: "Ohio", winnerScore: "34", loser: "Miami", loserScore: "30"),
    RivalryResult(year: "2007", winner: "Ohio", winnerScore: "38", loser: "Miami", loserScore: "29"),
    RivalryResult(year: "2008", winner: "Ohio", winnerScore: "28", loser: "Miami", loserScore: "3"),
    RivalryResult(year: "2009", winner: "Ohio", winnerScore: "28", loser: "Miami", loserScore: "7"),
    RivalryResult(year: "2010", winner: "Ohio", winnerScore: "34", loser: "Miami", loserScore: "13"),
    RivalryResult(year: "2011", winner: "Ohio", winnerScore: "21", loser: "Miami", loserScore: "14"),
    RivalryResult(year: "2012", winner: "Ohio", winnerScore: "27", loser: "Miami", loserScore: "24"),
    RivalryResult(year: "2013", winner: "Ohio", winnerScore: "41", loser: "Miami", loserScore: "16"),
    RivalryResult(year: "2014", winner: "Ohio", winnerScore: "24", loser: "Miami", loserScore: "17"),
    RivalryResult(year: "2015", winner: "Ohio", winnerScore: "34", loser: "Miami", loserScore: "3"),
    RivalryResult(year: "2016", winner: "Ohio", winnerScore: "17", loser: "Miami", loserScore: "7"),
    RivalryResult(year: "2017", winner: "Ohio", winnerScore: "45", loser: "Miami", loserScore: "28"),
    RivalryResult(year: "2018", winner: "Miami", winnerScore: "30", loser: "Ohio", loserScore: "28"),
    RivalryResult(year: "2019", winner: "Miami", winnerScore: "24", loser: "Ohio", loserScore: "21"),
    RivalryResult(year: "2021", winner: "Ohio", winnerScore: "35", loser: "Miami", loserScore: "33"),
    RivalryResult(year: "2022", winner: "Ohio", winnerScore: "37", loser: "Miami", loserScore: "21")
]


let rivalries = [
    Rivalry(name: "Anniversary Award", teams: [bowlingGreen, kentState], history: anniversaryAwardHistory) ,
    Rivalry(name: "Battle of I-75", teams: [bowlingGreen, toledo], history: battleOfI75History) ,
    Rivalry(name: "Battle of the Bricks", teams: [miami, ohio], history: battleOfTheBricksHistory),
    Rivalry(name: "Bronze Stalk", teams: [ballState, northernIllinois], history: bronzeStalkHistory),
    Rivalry(name: "CMU-EMU", teams: [centralMichigan, easternMichigan], history: CMUEMUHistory),
    Rivalry(name: "Michigan MAC Trophy", teams: [centralMichigan, easternMichigan, westernMichigan], history: [], michiganMACTrophy: michiganMACTrophyHistory),
    Rivalry(name: "Red Bird Rivalry", teams: [ballState, miami], history: redBirdRivalryHistory),
    Rivalry(name: "The Wagon Wheel", teams: [akron, kentState], history: wagonWheelHistory),
    Rivalry(name: "Victory Cannon", teams: [centralMichigan, westernMichigan], history: victoryCannonHistory) ,
]
